### PR TITLE
Update cPP_HCD.adoc

### PR DESCRIPTION
**Pull request by brianatricoh**
Issue 22 for cPP

### CODE REVIEW

**Comment by brianatricoh** [comment]
Please review and ensure consistent with changes made to the SD.

**Review by gcolunga — APPROVED** [review]
I have reviewed the changes and approve them.

**Comment by gcolunga** [comment]
Brian,

I have reviewed and approved the changes.

-Jerry
________________________________
From: brianatricoh ***@***.***>
Sent: Sunday, January 21, 2024 7:25 PM
To: HCD-iTC/HCD-iTC-Template ***@***.***>
Cc: Colunga, Gerardo ***@***.***>; Review requested ***@***.***>
Subject: [HCD-iTC/HCD-iTC-Template] Update cPP_HCD.adoc (PR #353)

CAUTION: External Email

Issue 22 for cPP

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/HCD-iTC/HCD-iTC-Template/pull/353

Commit Summary

  *   f5b88c0<https://github.com/HCD-iTC/HCD-iTC-Template/pull/353/commits/f5b88c0522c1a76b840e45efe8531037d894678e> Update cPP_HCD.adoc

File Changes

(1 file<https://github.com/HCD-iTC/HCD-iTC-Template/pull/353/files>)

  *   M cPP_HCD.adoc<https://github.com/HCD-iTC/HCD-iTC-Template/pull/353/files#diff-0954da0a0cd268196385e67368f0ff7a175669eeead93d2e5b39a0d7b190f0bd> (4)

Patch Links:

  *   https://github.com/HCD-iTC/HCD-iTC-Template/pull/353.patch
  *   https://github.com/HCD-iTC/HCD-iTC-Template/pull/353.diff

**Comment by brianatricoh** [comment]
I followed the link I received from Github and did the merge, so the cPP (pending any comments Alan has on the other issues) is complete.

-Brian

**Pull request merged**
